apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gradle17-cd
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/WexleyTan/gradle21_manifest.git
    targetRevision: master
    path: .
  destination:
    server: https://kubernetes.default.svc
    namespace: gradle17
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 2
