apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: gradle17-cd-certificate
  namespace: gradle17
spec:
  secretName: gradle17-cd-secret-tls
  commonName: alert-gradle.tinhlgkiddy.fun
  dnsNames:
  - alert-gradle.tinhlgkiddy.fun
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
